mod 'puppet-nginx'
mod 'puppetlabs-concat'
mod 'puppetlabs-stdlib'
mod 'pltraining/dockeragent'
mod 'puppetlabs-docker'
mod 'puppetlabs-apt'
mod 'puppetlabs-translate'
mod 'puppetlabs-powershell'
mod 'puppetlabs-reboot',
